### ISSUE TITLE
Build error 

### ISSUE THREAD

**Issue by maykiwo** [marcelmay/apache-oozie-exporter#1]
Have you any problem with maven central ?
I can't build the projet
thanks for you help

regards 

[INFO] Scanning for projects...
[WARNING] The project de.m3y.prometheus.exporter.oozie:oozie-exporter:jar:1.0-SNAPSHOT uses prerequisites which is only intended for maven-plugin projects but not for non maven-plugin projects. For such purposes you should use the maven-enforcer-plugin. See https://maven.apache.org/enforcer/enforcer-rules/requireMavenVersion.html
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Apache Oozie Exporter 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:3.0.0:clean (default-clean) @ oozie-exporter ---
[INFO] Deleting /tmp/oozie-exporter/apache-oozie-exporter-master/target
[INFO]
[INFO] --- buildnumber-maven-plugin:1.4:create (default) @ oozie-exporter ---
[INFO] Executing: /bin/sh -c cd '/tmp/oozie-exporter/apache-oozie-exporter-master' && 'git' 'rev-parse' '--verify' 'HEAD'
[INFO] Working directory: /tmp/oozie-exporter/apache-oozie-exporter-master
[INFO] Storing buildNumber: null at timestamp: 1522759406106
[WARNING] Cannot get the branch information from the git repository:
Detecting the current branch failed: fatal: Not a git repository (or any of the parent directories): .git

[INFO] Executing: /bin/sh -c cd '/tmp/oozie-exporter/apache-oozie-exporter-master' && 'git' 'rev-parse' '--verify' 'HEAD'
[INFO] Working directory: /tmp/oozie-exporter/apache-oozie-exporter-master
[INFO] Storing buildScmBranch: UNKNOWN_BRANCH
[INFO]
[INFO] --- maven-resources-plugin:3.0.2:resources (default-resources) @ oozie-exporter ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO]
[INFO] --- maven-compiler-plugin:3.7.0:compile (default-compile) @ oozie-exporter ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 5 source files to /tmp/oozie-exporter/apache-oozie-exporter-master/target/classes
[WARNING] /tmp/oozie-exporter/apache-oozie-exporter-master/src/main/java/de/m3y/prometheus/exporter/oozie/OozieCollector.java:[250,67] unchecked conversion
  required: java.util.Set<java.util.Map.Entry<java.lang.String,java.lang.Object>>
  found:    java.util.Set
[WARNING] /tmp/oozie-exporter/apache-oozie-exporter-master/src/main/java/de/m3y/prometheus/exporter/oozie/OozieCollector.java:[95,30] auto-closeable resource timer is never referenced in body of corresponding try statement
[WARNING] /tmp/oozie-exporter/apache-oozie-exporter-master/src/main/java/de/m3y/prometheus/exporter/oozie/HomePageServlet.java:[11,8] serializable class de.m3y.prometheus.exporter.oozie.HomePageServlet has no definition of serialVersionUID
[INFO]
[INFO] >>> inject-maven-plugin:1.0:inject (default) > :inject @ oozie-exporter >>>
[INFO]
[INFO] <<< inject-maven-plugin:1.0:inject (default) < :inject @ oozie-exporter <<<
[INFO]
[INFO]
[INFO] --- inject-maven-plugin:1.0:inject (default) @ oozie-exporter ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.451 s
[INFO] Finished at: 2018-04-03T14:43:28+02:00
[INFO] Final Memory: 26M/1447M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal de.m3y.maven:inject-maven-plugin:1.0:inject (default) on project oozie-exporter: Value is null for injection Injection{value='null', pointCut='de.m3y.prometheus.exporter.oozie.BuildInfoExporter.getBuildScmVersion', pointCuts=null} -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by marcelmay** [comment]
Thx for the info.

The error happens because you're building not from a Git checkout. The Maven inject plugin tries to inject the Git hash as a source code management version:

```
[ERROR] Failed to execute goal de.m3y.maven:inject-maven-plugin:1.0:inject (default) on project oozie-exporter: Value is null for injection Injection{value='null', pointCut='de.m3y.prometheus.exporter.oozie.BuildInfoExporter.getBuildScmVersion', pointCuts=null} 
```

Build should work if you use a git checkout and build then.

I'll publish a 1.0 release soon, available on Maven Central.

**Comment by marcelmay** [comment]
Just added defaults, so that you do not require a git checkout.

**Comment by maykiwo** [comment]
Thanks for reply.

I'm not sure how build with defaults?
I've just downloaded the zip file and try to build with 'mvn clean install '

Thanks

**Comment by marcelmay** [comment]
Yes, a `mvn clean install` should work now when just downloading the sources.

For your info: I added a 1.0 milestone and some issues - as a roadmap to the upcoming 1.0 release.

I also uploaded a [Snapshot](https://oss.sonatype.org/content/repositories/snapshots/de/m3y/prometheus/exporter/oozie/oozie-exporter/1.0-SNAPSHOT/).

**Comment by maykiwo** [comment]
Thanks for your work.

Your run_example.sh is not found

https://github.com/marcelmay/apache-oozie-exporter/blob/master/run_example.sh

Code : 404

Thanks

**Comment by marcelmay** [comment]
Sorry, that was a copy-and-paste error from another exporter.

Check out the [section for running the oozie exporter](https://github.com/marcelmay/apache-oozie-exporter#user-content-installation-and-configuration).

After building locally, the exporter will show the options when invoking without args:
```
java -jar target/oozie-exporter-1.0-SNAPSHOT.jar
```

So you could invoke the  exporter for a locally running Oozie (available at http://localhost:11000/oozie) and without authentication like this:
```
java -jar target/oozie-exporter-1.0-SNAPSHOT.jar \
       -web.listen-address=localhost:7772 \
       -oozie.url=http://localhost:11000/oozie
```
